intern/maze: allow user to specify number of tests to replace

diff --git a/intern/files/maze/replace_tests b/intern/files/maze/replace_tests
--- a/intern/files/maze/replace_tests
+++ b/intern/files/maze/replace_tests
@@ -2,6 +2,18 @@
 
 TOTAL_TEST_CASES=10
 
+# see if the number of tests to replace is given
+if (test $# -gt 1)
+then
+    echo "Only required one optional argument: number of test to replace"
+    exit 1
+elif (test $# -eq 1)
+then
+    TOTAL_TEST_CASES=$1
+fi
+
+echo "Replacing $TOTAL_TEST_CASES tests."
+
 rm -f test_inputs/*.bmp
 
 for i in `seq $TOTAL_TEST_CASES`
